apiVersion: v1
kind: ConfigMap
metadata:
  name: inference-api-config
data:
  APP_ENV: {{ .Values.env.APP_ENV | quote }}
  LOG_LEVEL: {{ .Values.env.LOG_LEVEL | quote }}
  MODEL_DIR: {{ .Values.env.MODEL_DIR | quote }}
  MODEL_VERSION: {{ .Values.env.MODEL_VERSION | quote }}
  PREPROCESS_VERSION: {{ .Values.env.PREPROCESS_VERSION | quote }}
